### ISSUE TITLE
[Suggestion] Almost Automatic CHANGELOG

### ISSUE THREAD

**Issue by kevinmatthes** [ammarabouzor/tui-journal#11]
It is a good practice to maintain a CHANGELOG in order to document the changes between versions.  Often, one major problem is how these CHANGELOGs are maintained; some policies trigger numerous unnecessary Merge Conflicts and thus slow down the development critically, other ones require much effort as the maintainers are the only ones who are allowed to edit it.  But fortunately, there is a lot of software to make a CHANGELOG almost completely self-maintaining.

I would like to offer you to set up everything for this project such that:

- CHANGELOG entries are created *automatically* from the committed changes on PR.
- the CHANGELOG is assembled from the submitted fragments *on release*.

Would you be interested in such a feature for TUI-Journal, @AmmarAbouZor?

**Comment by AmmarAbouZor** [comment]
I think this would be great for this app since it's already growing and has a big roadmap. I appreciate your help since I'm still relatively new to GitHub workflows.

I have small questions for this automation: 
- Would I be able to edit the CHANGELOG manually? say adding an animation or something
- Is there some kind of documentation for it, so we can know how to use and modify it.

**Comment by kevinmatthes** [comment]
> Would I be able to edit the CHANGELOG manually? say adding an animation or something

Yes, you be able to do so.  The CHANGELOG is just a simple plain text file, just as the source code.  You are free to edit the whole file as you wish -- except for one line which is the Magic Comment of the technology I would like to suggest.  This Magic Comment controls where the application is going to put the new CHANGELOG entries to.

> Is there some kind of documentation for it, so we can know how to use and modify it.

Yes, there is documentation for the two applications I would like to suggest.  The first application's documentation can be found by clicking its "docs" badge in its README.  The second application is written by me, so you can just ask me.  Besides, I already have experience with configuring this technology, so the setting it up is rather routine for me.

First of all, the overall maintenance is done by Scriv (https://github.com/nedbat/scriv).  It is written in Python 3 and will take care about the CHANGELOG assembly.  Thereby, small files named "fragments" will be read and processed, i.e. sorted by category, and finally put into the main CHANGELOG file.  Scriv defaults to reStructured Text as output format, so I recommend using this format.  As I wrote above, you put a Magic Comment somewhere in your CHANGELOG and Scriv will insert the assembled information there.  At option, you can also deploy the generated CHANGELOG to GitHub Releases but I do not have any experiences with this feature, yet, so I cannot give you any advice on that.

There are plenty of interesting options to automate the fragment collection, which is synonymous with the CHANGELOG assembly.  For the basic setup, I would recommend a workflow for manual dispatch such that you only need to click a button and your CHANGELOG is updated automatically.

Scriv itself also allows for the creation of the fragments it is going to process.  However, it will just give you something like a form you need to fill out by hand.  This is not only additional effort, it might also cause errors, e.g. if you fill out the form before making the changes and then recognise that you need to revert them later on after having them already committed; it is easy to forget to also adjust the Scriv fragment accordingly.

I wrote a Rust application, Aeruginous (https://github.com/kevinmatthes/aeruginous-rs), which will browse your commit messages and create you a Scriv fragment with content based on the commits' first paragraphs.  The idea is to harvest the changes submitted by a PR when it is raised; this can be configured to be the workflow's trigger condition.  Within the workflow, you can set any options you like to Aeruginous to create the Scriv fragments just as you require them.  If the current options should not suffice, I can add more.

And finally, also the CHANGELOG format has a documentation.  I experienced Keep a Changelog (https://keepachangelog.com/en/1.0.0/) to be a very popular format -- even Scriv itself uses it --, so I would like to suggest this one.  I use it for many projects myself and when it came to the question of choosing a format, this one was always the preferred solution.

The next step would be to discuss your requirements for the CHANGELOG and how they can be made into GitHub Action workflows and calls to Aeruginous.

**Comment by AmmarAbouZor** [comment]
Thanks for the helpful and detailed infos.
It looks very interesting and helpful. I want to familiar myself a little bit about this topic and I'll get back to it very soon.

**Comment by AmmarAbouZor** [comment]
So I had a look on the both repository. Awesome  work @kevinmatthes :100: 
We can give a try here and make adjustments along the way if needed.
So here are my initial thoughts:
- I'm thinking of a simple CHANGELOG without much verbose information. 
- We can trigger the generation on pull request put I would like to see the generated data before merging the pull request if this possible.
- I would like to hear from you how would you do it since you wrote one tool and have much more experience with that

**Comment by kevinmatthes** [comment]
> I'm thinking of a simple CHANGELOG without much verbose information.

Both Scriv and Aeruginous think their CHANGELOG fragments in categories.  You will need to decide which categories you would like to have in your CHANGELOG.

The already mentioned Keep a Changelog has the following six categories:

- Added
- Changed
- Deprecated
- Fixed
- Removed
- Security

You are free to add further ones as well as to remove those you would not like to have in your CHANGELOG.  However, it is better having too many categories than too few as Scriv will simply skip empty categories on assembly.  If you never deprecate features, for instance, there will never be an entry in the "Deprecated" category although it can be still kept configured without causing problems.

When using Aeruginous for the fragment creation, the users submitting commits control the verbosity of the resulting entries.  Aeruginous will split the commit messages' first paragraphs at the occurrence of a given delimiter into a category name and the entry for that category.  If users keep the first paragraph of their commits brief, the entry will be short, as well.  Furthermore, you are allowed to enforce that at most $n$ commits will be harvested in order to prevent huge fragments.  You can also configure GitHub Apps and Actions to enforce certain rules regarding the commit messages of PR commits, such as that they are allowed to consist of at most 100 characters, for example.

There are plenty of options, so the best would be to think about a sample section of your CHANGELOG whose appearance we can turn into workflows, then.  The most important aspect are the categories, for the beginning; the other details can be adjusted later on.

> We can trigger the generation on pull request put I would like to see the generated data before merging the pull request if this possible.

It is possible to see the generated fragment before merging the PR.  The fragment is a file on its own -- a new file, to be exact.  You just select the "Files changed" tab in a PR where you can see all edited files.  Since the fragments will be always put into one certain directory, the new fragment is very easy to identify.

Furthermore, there are options to enforce that all changes are reviewed by you before the PR can be merged.  This is called CODEOWNERS:  a small configuration file where you state that all files in this repository are your intellectual property.  To set it up, just put the following line into a new file named `.github/CODEOWNERS`.

```
* @AmmarAbouZor
```

Now, GitHub will request your review for every PR that is raised and *should* also block merging before you have approved the PR.  To make absolutely sure that merging is blocked until then, go to the settings and create a branch protection rule for the `main` branch where you explicitly require CODEOWNERS to approve the PR, at first.

> I would like to hear from you how would you do it since you wrote one tool and have much more experience with that

- We initialise Scriv.  This is the creation of its configuration file *within* its default target directory.  You can set the target directory to any directory which exists but in my opinion, the default setting `./changelog.d/` should suffice in most cases.
- In the configuration file for Scriv, we set the categories.  Decide which ones you would like to have and we enter them there.  Furthermore, we set the appearance of the CHANGELOG headings to the following style.  This style is required by Aeruginous and is also a sane configuration; "CHANGELOG" will be the top-level heading (h1 in HTML terminology), "Version" level 2 (h2), and "Category" level 3 (h3).  I can also make Aeruginous more flexible regarding this, but that might take some time.

```rst
CHANGELOG
=========

Version
-------

Category
........
```

- We set up the collection workflow for CHANGELOG assembly.  On workflow dispatch, i.e. you click a button, Scriv will update the CHANGELOG.  This can be combined with further documentation and maintenance technologies in the long term, at option, like version number incrementing systems.
- We configure the workflow for the fragment creation on PR.  There, we mirror the categories we set up for Scriv to Aeruginous.  It has a category checker such that it will only respect the given ones because it does not evaluate Scriv's configuration.  This was a design decision make Aeruginous more flexible regarding and independent from the actual fragment processing back-end.  The PR fragment creation workflow will only work for *you* automatically and will fail for others.  This is a limitation of GitHub Action workflows due to security reasons:  a new commit would be pushed to another repository.  If it was your fork, you would receive commits authored by someone else; I can understand that this should not be possible and I agree with denying that.  Thus, we add a clickable button for that workflow such that users can invoke the fragment creation when they are ready with their work.
- The other way around is to require contributors to have Aeruginous installed such that they can create their fragments locally and push them to their branches manually.  This would prevent failing workflow runs.
- Finally, we can also use Scriv's fragment creation.  This will create an *empty* "form" you would need to fill out manually.  I have created an Action therefore which should be invoked by a clickable button.

One last note on the PR auto-creation:  if a PR is already created and the GitHub Actions bot pushes to the head branch, the CI steps are *not* going to be invoked automatically.  This is important for "Automatic Merging" of the branch because it just will not work; you would need to close and re-open the PR instead, for instance, to trigger the CI to run on a commit by the GitHub Actions bot.

**Comment by kevinmatthes** [comment]
By the way:

- Aeruginous v1.1.2 now also has a shortcut option for Keep a Changelog categories.  This might help in the configuration.
- Aeruginous allows since v1.1.0 for the definition of links in the resulting fragments.  One repository relying on Aeruginous' fragment creation uses this feature to embed the PR number into the fragment.

**Comment by kevinmatthes** [comment]
I experimented with various additional output formats for the fragments in the past day; how about a RON CHANGELOG?

The workflow would stay basically the same:  you create a fragment per PR and merge all fragments with the CHANGELOG on release.  One could now argue that the Rusty Object Notation (RON) would be more appropriate for a Rust project.  It would work purely with Aeruginous itself without requiring any other tools although you could migrate to another format later on, at option.  For example, you could then export the RON CHANGELOG to a format supported by Scriv.

Would you be interested in such a feature?

**Comment by AmmarAbouZor** [comment]
Thanks for taking the time explaining every aspect and option we have here.
So let's set the simple points at first...  I think we can use all the six provided categories and set the configurations file for Scriv as suggested so it works with Aeruginous.

Now for the automation part... I have another suggestion for Aeruginous, how about adding a function to it to make it run inside a scheduled pot by the repo maintainers and not inside the PRs. Here are what I have in mind:
- Aeruginous keeps track to the last checked commit in main branch
- When It runs it checks if there are new commits/PRs and then creates the fragments and updates the last checked commit
- The automation can be done in to different ways:
1 - If Aeruginous detects changes, it creates a branch itself with a configurable name, creates the fragments and commits them with a configurable commit message as well, then optionally creates a new pull request using GitHub and optionally approves it.
2- Makes Aeruginous do one job by adding two simple cli commands, one to check if there changes and the other to generate the fragments. Like that you leave creating the branches and committing the changes to the automated pipeline. This gives more flexibility but the maintainer should create more parts of the workflow themselves.
- Aeruginous can retrieve git credentials through environmental variables

I find it more adaptive this way by keeping the CHANGELOG work for the maintainers only and enforce less stuff on the contributors. 
@kevinmatthes What do you think about this workflow?


> I experimented with various additional output formats for the fragments in the past day; how about a RON CHANGELOG?

If you think it's useful to use a RON CHANGELOG then sure we can apply it here. This has advantageous to not lock your tool with Scriv only and makes easier to add support to other backend tools along the way

**Comment by kevinmatthes** [comment]
Okay, I will prepare the basic setup for these requirements! :+1:

Please note that the pure RON CHANGELOG might take some time (I expect two weeks, maybe less), so I would prepare everything for the reStructured Text setup, for the beginning.  When I finished the work on the RON CHANGELOG feature, I will translate all fragments by hand into RON such that we can apply the RON version, if you would like to switch, then.

**Comment by AmmarAbouZor** [comment]
Take your time. At end we do this in our free time without any obligations :+1:
