### ISSUE TITLE
[Suggestion] CHANGELOG Fragment Creation Once on Release?

### ISSUE THREAD

**Issue by kevinmatthes** [AmmarAbouZor/tui-journal#202]
Technically, it would suffice to harvest all changes as usual *once, on release,* such that one big fragment would be generated instead of multiple ones.  That fragment would not even be saved in the repository as it would be processed (and, thus, removed) right after its creation during the RONLOG assembly.  Aeruginous would therefore harvest all changes from the latest tag on, then.

Would you consider this a useful enhancement, @AmmarAbouZor?  If so, I will adjust Aeruginous accordingly and suggest you the corresponding changes to your CI after releasing the respective new version of the tool.

(By the way:  the latest version of Aeruginous fixes one of the most annoying bugs RONLOGs had so far -- the random re-ordering during the assembly of a new section; see https://github.com/kevinmatthes/aeruginous-rs/discussions/795.)

**Comment by AmmarAbouZor** [comment]
Hi @kevinmatthes Thanks for the suggestion.
This looks promising, it sure would be easier to have less work with the PRs for RONLOG.
You can gladly make the adjustments here and there, I would really appreciate it :smiley:

**Comment by kevinmatthes** [comment]
I prepared the necessary adjustments in Aeruginous for the suggested feature; see https://github.com/kevinmatthes/aeruginous-rs/pull/797.  Please tell me what you think about it and if there might be changes required.

**Comment by AmmarAbouZor** [comment]
I checked the changes in the PR. I think it's great and should work as we wanted
