### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by DRM-Free** [AmmarAbouZor/tui-journal#206]
I would like the buffer to be saved automatically upon closing external editor. Quitting vim with :wq then saving the buffer again with s seems unintuitive.

**Comment by AmmarAbouZor** [comment]
I think It would be better to add an option in the app configuration for auto save upon closing closing the external editor. 

The reason that the file isn't automatically saved at that point is that there is no other way to recover the data after it saved in the editor.
