### ISSUE TITLE
[Feature Request] Sorting

### ISSUE THREAD

**Issue by donovanglover** [AmmarAbouZor/tui-journal#264]
Found tui-journal from nixpkgs and think it's cool. Would love to see a sorting feature. For example:

- Sort by creation time
- Sort by last modified time
- Sort by title

Seems like prior discussion was in https://github.com/AmmarAbouZor/tui-journal/issues/9#issuecomment-1560556646 so I'm making a new issue as suggested.

**Comment by AmmarAbouZor** [comment]
I think adding sort function could be helpful in some situations (at least to toggle between ascending and descending). I'll work on a pop-up to specify the available sorting options (title and date) in the next few days.

> Sort by creation time
Sort by last modified time

We don't save this data for the journals yet. There is only one date that will default to the creation day of the journal and the users can change it as they want.
I actually don't see a huge benefit to save the creation date and last modification date for simple journals. Maybe It would be something to do in the future but currently I'll postpone it for now.

**Comment by donovanglover** [comment]
Keeping it simple sounds good to me :+1:
