### ISSUE TITLE
[Feature Request] Search

### ISSUE THREAD

**Issue by kevinmatthes** [AmmarAbouZor/tui-journal#27]
It would be useful to be able to search all journals for some text.  For the implementation, I would like to suggest to query the back-end for the search text and to select the (first) journal which contains that text or to highlight all journals' names in the left-hand sidebar which contain that search text.

For the SQL back-end, I would like to suggest to use `select title from entries where content like "%{}%"` as template for the query in order to determine all matching journals; in order to prevent SQL injections, you could replace all non-alphanumeric characters by the SQL placeholder `%` in the search text.  Note:  sqlite3 is *not* case sensitive regarding text search with placeholders.

**Comment by AmmarAbouZor** [comment]
I think these could be valuable as a basic search to find some keywords. We can create a search prompt and then select the first journal which content has the text.

Then after having a concept to filter the journals which we discussed in #9 , I would apply this search function as a filter criterion too to show only they journals with the text in their contents
