### ISSUE TITLE
Reordering entries

### ISSUE THREAD

**Issue by orhun** [AmmarAbouZor/tui-journal#270]
I would like to have special keys to reorder the entries, for example:

- Ctrl + K -> move the entry to one entry above
- Ctrl + J -> same, but one entry below

My reasoning is that I want to sort my notes by their importance/priority. 

Related: #264

**Comment by AmmarAbouZor** [comment]
I think we could add a new optional field for the entries called "priority" with a number value. 
Then we can apply it as an option in the sorting popup from #264. 
I think having the priority visible and controlled by the user would make managing the ordering more straight-forward

**Comment by orhun** [comment]
Yes, that makes sense!
