### ISSUE TITLE
Toggle full-screen mode

### ISSUE THREAD

**Issue by orhun** [AmmarAbouZor/tui-journal#271]
Is it possible to hide the content view (on the right)? I usually don't take notes there and the titles of the entries are enough for me to remember the context. So the content is taking a huge amount of space in my terminal and it is usually empty.

It would be nice to have a special key to toggle the visibility of content. I'm happy to submit a PR if you find this applicable.

**Comment by AmmarAbouZor** [comment]
I think having a shortcut to toggle full-screen mode for the active control would be the best approach. With that the users could go in full-screen mode for the built-in editor too.

You can gladly submit a PR for it, or I can do it in the next few days too...

Here are some specification...
- The toggle full-screen shortcut should work on both the journals list and the editor, but not in edit mode in the editor.
- The footer should be always visible
- The command to switch between the active controls should exit full-screen mode if it active before
- Toggle full-screen mode should be a global command, so it will be inserted automatically in the help-popup
