### ISSUE TITLE
Changelog-Assembly doesn't work anymore

### ISSUE THREAD

**Issue by AmmarAbouZor** [AmmarAbouZor/tui-journal#286]
After the latest changes I've encountered and error while running the changelog-assembly workflow 
Here is the [link to the failed pipeline](https://github.com/AmmarAbouZor/tui-journal/actions/runs/7423398030)

@kevinmatthes Could you please have a look on it

**Comment by kevinmatthes** [comment]
I will have a look on it. :+1:

**Comment by kevinmatthes** [comment]
Missing `v` prefix in workflow.

**Comment by kevinmatthes** [comment]
See #287 for a fix.

**Comment by AmmarAbouZor** [comment]
@kevinmatthes I've started a new workflow but I've got the same error message. 
Here is a [link to latest pipeline run](https://github.com/AmmarAbouZor/tui-journal/actions/runs/7427052679)

**Comment by kevinmatthes** [comment]
I set the correct value to the wrong option. :facepalm:

It should have been `-T` instead of `-S`.

**Comment by kevinmatthes** [comment]
#288

**Comment by AmmarAbouZor** [comment]
@kevinmatthes The old issues seems to be working but we've got a new error message now

**Comment by kevinmatthes** [comment]
```yml
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
```

Another thing I forgot about. :facepalm:

**Comment by kevinmatthes** [comment]
#289

**Comment by kevinmatthes** [comment]
Related documentation page:  https://github.com/kevinmatthes/aeruginous-rs/discussions/1029.
