### ISSUE TITLE
[Feature Request] JSON Back-end Compression

### ISSUE THREAD

**Issue by kevinmatthes** [AmmarAbouZor/tui-journal#30]
Users choosing the JSON back-end might notice an inconveniently increasing file size of the back-end the more journals are added.  I would like to suggest to compress the JSON file if a certain file size threshold was exceeded.  Regarding the compression algorithm, I would like to suggest Brotli (https://github.com/google/brotli) which is enhanced for compressing plain text files, like the JSON back-end, and achieves a convenient compression ratio.  Rust bindings are available:  https://github.com/dropbox/rust-brotli.

**Comment by kevinmatthes** [comment]
A good use case of JSON would be to store exactly one journal for insertion into the database.  For example, if users should choose to export a journal with `.json` as extension, the JSON representation of that journal could be used instead of just dumping the plain text into a file.  Then, on startup of the application, the path to a valid JSON back-end can be provided such that its data will be inserted into the connected database.

Thus, the JSON back-end could become a journal exchange functionality across multiple SQLite back-ends.

**Comment by AmmarAbouZor** [comment]
For this use-case I'm planning to provide an export/import functions for the journals, and the file format will be a json one. I thinks this will be fit in the road map: Multi-select >> Export/Import

I'll keep this issue and we can discuss it further after the previous feature are implemented to check if we still need it then

**Comment by AmmarAbouZor** [comment]
@kevinmatthes I would like to hear from you if there is use-cases that aren't covered with the implemented Multi-Select >> Export/Import functions or if we can close this issue

**Comment by kevinmatthes** [comment]
I think we can close this issue for now; if there should be any not yet covered use cases, we can create another issue.
