### ISSUE TITLE
MSRV

### ISSUE THREAD

**Issue by 0323pin** [AmmarAbouZor/tui-journal#309]
Hi,
NetBSD package maintainer here. What's the MSRV for `tui-journal`?

My system, NetBSD 10.99.10, Rust-1.75.0
```
===> Installing dependencies for tui-journal-0.8.0
==========================================================================
The following variables will affect the build process of this package,
tui-journal-0.8.0.  Their current value is shown below:

        * SSLBASE = /usr
        * SSLCERTBUNDLE (not defined)
        * SSLCERTS = /etc/openssl/certs
        * SSLDIR = /etc/openssl
        * SSLKEYS = /etc/openssl/private

You may want to abort the process now with CTRL-C and change the value
of variables in the first group before continuing.  Be sure to run
`/usr/bin/make clean' after the changes.
==========================================================================
=> Tool dependency mktools-[0-9]*: found mktools-20220614
=> Tool dependency pkgconf-[0-9]*: found pkgconf-2.0.3
=> Tool dependency cwrappers>=20150314: found cwrappers-20220403
=> Tool dependency checkperms>=1.1: found checkperms-1.12
=> Build dependency rust>=1.56.1: found rust-1.75.0
===> Skipping vulnerability checks.
WARNING: No /usr/pkg/pkgdb/pkg-vulnerabilities file found.
WARNING: To fix run: `/usr/pkg/sbin/pkg_admin -K /usr/pkg/pkgdb fetch-pkg-vulnerabilities'.
===> Overriding tools for tui-journal-0.8.0
===> Extracting for tui-journal-0.8.0
=> Extracting local cargo crates
===> Patching for tui-journal-0.8.0
===> Creating toolchain wrappers for tui-journal-0.8.0
===> Configuring for tui-journal-0.8.0
=> Checking for portability problems in extracted files
===> Building for tui-journal-0.8.0
   Compiling libc v0.2.152
[...]
   Compiling git2 v0.18.1
   Finished release [optimized] target(s) in 8m 21s
```

One of our build servers running Rust-1.74.1, http://www.ki.nu/pkgsrc/reports/current/NetBSD-9.0/20240115.1324/tui-journal-0.7.0/build.log

Thanks!

P.S: Yes, my build is for 0.8.0 and the server build for 0.7.0

**Comment by AmmarAbouZor** [comment]
Hi @0323pin . Thanks for submitting this issue.
The MSRV is 1.75.0 from Version 0.7 upward, because I've started using the native support for async traits from Rust which introduced in version 1.75.0.

I'll add this to the `cargo.toml` file to prevent any confusion

**Comment by AmmarAbouZor** [comment]
I've added the minimum rust support to `cargo.tom` and created a path release. Hopefully this is enough to prevent any confusion in the future

**Comment by 0323pin** [comment]
Thank you!

It wasn't really a "confusion" 😀
It's just that we usually are on Rust latest '-1' and it's good to know what to expect.

**Comment by 0323pin** [comment]
Close?

**Comment by AmmarAbouZor** [comment]
> Thank you!
> 
> It wasn't really a "confusion" 😀 It's just that we usually are on Rust latest '-1' and it's good to know what to expect.

It was actually a good learning opportunity to know that this we can set this info inside the project manifest :smile: 
I'll close the issue then :+1:
