### ISSUE TITLE
Switch to vim motions

### ISSUE THREAD

**Issue by HalanoSiblee** [AmmarAbouZor/tui-journal#386]
Copying text to system clipboard with CTRL+V give me this
![image](https://github.com/AmmarAbouZor/tui-journal/assets/70325026/ef885c8c-e550-4967-88a1-5daa5d6790fc)
What if it's using vim motions it would be faster and easier
I'm not able to copy text from tjournal.

**Comment by AmmarAbouZor** [comment]
Thanks for submitting the issue...
I didn't know that it's possible to select the text from the editor in the edit mode via shift+arrows. For that I need to unable the copy shortcut in editor edit mode... I think this should be enabled and will be working on it soon.

For now you can copy the text visual mode only, and to activate this mode you need to have the editor as your active control but nut in the edit mode, then you can enter visual mode via the v key and form there you can use the Ctrl+V to copy the text.

I think it would good to have an option to sync the system clipboard with the app clipboard as a new feature. I'll work on it soon.
