### ISSUE TITLE
Show the selected index and count

### ISSUE THREAD

**Issue by orhun** [AmmarAbouZor/tui-journal#402]
It would be nice to show how many entries I have + the index of the selected one 🐻 

Happy to contribute this feature if you think it's appropriate.

**Comment by AmmarAbouZor** [comment]
Thanks for the suggestion and the willingness to contribution. It would be surely very nice to have this information on the screen. Another use case for this feature would be when a filter is applied then we can find out how many items meets the filter criteria instantly, without having to count the items manually.
 
I think it have a good place in the bottom border of the journals list if that's possible, sure I'm open for other suggestion about where to place it.
Another point to experiment with is additionally to show how many journals are selected only when selected mode is activated, but it may be not enough room for all the information. You can experiment with that and keep it if it fits and if it's easy to implement.

As always, I'm looking forward for your great contributions :100:

**Comment by orhun** [comment]
Implemented it in #403 - kept it simple. Let me know what you think!
