### ISSUE TITLE
Support colored tags

### ISSUE THREAD

**Issue by orhun** [AmmarAbouZor/tui-journal#407]
title ^

It would be pretty sweet to add custom categories (or tags) and categorize things 🐻

**Comment by AmmarAbouZor** [comment]
Thanks for the suggestion. Currently, it's possible to add tags to the entries and the users can either type a new tag or select one from the already defined one in the file. This is possible from the journal pop-up (On create and edit).
After tags are set they will be shown in the entries list and it's possible to filter the journal according to the tags.

The coloring is messing though, and would be interested to add such an option to color the background of the tags. I'll add it to the road map :+1:

**Comment by orhun** [comment]
I really feel the need for this feature these days, can you possibly prioritize in the roadmap? I'm also happy to work on it if you can give me some tips :)

**Comment by AmmarAbouZor** [comment]
@orhun This is the next feature I'll be working on, let's hope I got some time this week to start with it.

For the implementation I was thinking to manage and save the colors of the tags separately from the journals themselves. Like we can add a separate popup for assigning tags to colors, and we can save this map in each project in a separate table than the journals as well. For that we need an implementation on each backend + a migration step for the existing files.

Here are some other points:
* We would need an export/import function for those colors, to transfer them between files easily.
* For each tag we will need to assign background and foreground colors too to make it possible for users to keep the tags readable by changing the foreground color.
* We need to save the colors in text format (serialized json maybe?) to support terminal colors + RGB ones.

Please add points here if you have any other point mind here, so we have the requirements list ready when starting to implement it.

**Comment by orhun** [comment]
That sounds good! I'm not super familiar with the internals/implementation but maybe the feature roadmap would be:

- Colorize the same tags with the same (random) color (good enough as a first step)
- Support assigning colors to a tag on the "create journal" menu
- Add a new popup menu specifically for tweaking colors/tags

I'm also all for what you're planning for it :)

**Comment by AmmarAbouZor** [comment]
Thanks for the suggestion. I think I'll provide random color for tags at first because I can do that relatively fast without the need for a lot of testing for now, then I can work when I have enough time on the management for coloring the tags with all the data migrations and the new UI views

**Comment by orhun** [comment]
Sounds perfect!
