### ISSUE TITLE
No config.toml file or tui-journal directory when installing through nixpkgs

### ISSUE THREAD

**Issue by Arqamz** [AmmarAbouZor/tui-journal#420]
Im on nixos and i installed tui-journal as such in my configuration.nix file
```
  environment.systemPackages = [
    pkgs.tui-journal
  ]
  ```
  
However I can't find the config file OR the tui-journal directory anywhere on my system.

**Comment by AmmarAbouZor** [comment]
Configuration file wouldn't be automatically generated but this is achievable with CLI arguments directly:
```bash
tjournal -w  
```
This will write the current configurations to the standard config directory (normally $HOME/.config on linux) within the directory 'tui-journal', and then it will start the app.

Besides that, you have the command `tjournal print-config` which will print the current configurations to the standard output, which allow users to check the current path for their data files.

Note: I didn't bundle the app to `nixpkgs` and the maintainer for it haven't contacted me, but I'm happy that this app is already available for the great nix package manager

**Comment by Arqamz** [comment]
Wow that was really quick and helpful! Great app, I will definitely be using it alott. Just a tiny note, not everyone knows 'Emacs binds', so you could maybe list those bindings in the editor keybinds page?

**Comment by AmmarAbouZor** [comment]
Glad that it help :relaxed:

**Comment by Arqamz** [comment]
Thank you!

**Comment by AmmarAbouZor** [comment]
Let's keep this issue open as reminder for adding emacs keybindings
