### ISSUE TITLE
Add a way to select storage file

### ISSUE THREAD

**Issue by RyaIsCoding** [AmmarAbouZor/tui-journal#460]
Not sure if its a niche thing but I really like this tool but I also want to have multiple "notebooks" with different things in them. At the moment I have two different files that I select between by editing my config file to show which ever folder I like but I was wondering if it would be possible to have this as an option inside the app?

**Comment by AmmarAbouZor** [comment]
Hi, this is already possible via command line arguments. You can use the CLI arguments `tjournal -j <FILE PATH>` for json files and `tjournal -s <FILE PATH>` for sqlite db files.

Here is a quote from the output of the help command:
```bash
Options:
  -j, --json-file-path <FILE PATH>    Sets the entries Json file path and starts using it
  -s, --sqlite-file-path <FILE PATH>  Sets the entries sqlite file path and starts using it
```

Please let me know if this solved your issue so we can close this one :wink:

**Comment by RyaIsCoding** [comment]
O this is actually perfect thank you
