### ISSUE TITLE
Case insensitive search

### ISSUE THREAD

**Issue by chaiNeehujui** [AmmarAbouZor/tui-journal#490]
Hello!

Currently, the both search functionalities, filter and fuzzy-search, are case-sensitive, which can be limiting for users who may not remember the exact casing of the terms they are searching for. Implementing a case-insensitive search would improve the user experience by allowing users to find results regardless of how they input the search terms. 

Would it be possible to consider this feature in a future update?

Thank you for your hard work on this project!

**Comment by AmmarAbouZor** [comment]
Very thanks for the suggestion. It makes sense for sure to have the option for case insensitive search in filter and Fuzzy finder... 
I'll investigate on the possible solutions:
* Option in configuration or in popup controls
* Which option should be the activated by default.

I'll start looking into it that after fixing publishing on homebrew when I get time for it :+1:
