### ISSUE TITLE
use of unstable library feature 'error_in_core'

### ISSUE THREAD

**Issue by 0323pin** [AmmarAbouZor/tui-journal#497]
Hi,

NetBSD package maintainer here. I was about to update to yesterdays release and decided to check on the state of the previous one.

It appears the MSRV stated in [Cargo.toml](https://github.com/AmmarAbouZor/tui-journal/blob/537c0a9b12ba2a260470df6aab5defb93f38ad85/Cargo.toml#L12) no longer applies, see the [buildlog](http://shadow.netbsd.org/pub/pkgsrc/packages/reports/HEAD/NetBSD-10.0-x86_64/20241115.2326/tui-journal-0.12.1/build.log) from our build machines. Obviously, I did not see this as I'm using Rust-1.82 while the most recent version is officially 1.80.

Would it be possible to keep the actually required MSRV up-to-date? It would help maintaining the package and save the time required for potential downgrades. Thank you.

**Comment by AmmarAbouZor** [comment]
You are right I must include the minimal supported Rust Version in my CI checks so I found out about them before anything get released. This will be included before the next release for sure :+1: 
The breaking change came this time from one of the dependencies and I wasn't aware of it

**Comment by 0323pin** [comment]
@AmmarAbouZor Does it require 1.82 or, is it enough with 1.81? We should get 1.81 in tree in a few days and it's nor worthy a package downgrade. But, if it requires 1.82, I need to downgrade the package before the next stable branch.

**Comment by AmmarAbouZor** [comment]
The feature `error_in_core` is introduced in Rust version 1.81 [link](https://blog.rust-lang.org/2024/09/05/Rust-1.81.0.html#coreerrorerror). Therefore, it should work with version 1.81. 
It stills not 100% sure because I didn't run the build on manually with version 1.81

**Comment by 0323pin** [comment]
Thank you!
