### ISSUE TITLE
[Bug Report] Application of Discontinued GitHub Action

### ISSUE THREAD

**Issue by kevinmatthes** [AmmarAbouZor/tui-journal#55]
In line 55-59 of release.yml, you call the Action `actions-rs/toolchain` which is discontinued; see https://github.com/actions-rs/toolchain/issues/216.  Rust is already installed on the runner, you can always call `rustup update` for a self-upgrade and add components manually.

**Comment by AmmarAbouZor** [comment]
Thanks for catching the bug @kevinmatthes 
The release pipeline is still a work in progress since it hasn't run until now successfully. Actually I'm not happy with it until now, and I intend to make some other improvements there too.

I think then I can remove the whole 'Install Rust' part since it's already installed

**Comment by kevinmatthes** [comment]
I found another discontinued Action in the workflow; this is the minor bug I mentioned in https://github.com/kevinmatthes/aeruginous-rs/issues/337.  The release creation Action is a public archive, so there are not going to be any updates, anymore.

However, I think I found a working alternative:  https://github.com/softprops/action-gh-release.  I tested it for the release of Aeruginous v2.2.1 and it worked without any problems.  I even found out how to customise the automatically generated release notes:  https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes.

What do you think about this?

**Comment by AmmarAbouZor** [comment]
I think it's better to write it from scratch using the new action than trying to fix the current one.

I can take a look on your solution for inspirations and change the one here, or you can gladly implement it here too if you want to :smiley:

**Comment by AmmarAbouZor** [comment]
I'll give it a try, since I'm intending to make a minor release today

**Comment by AmmarAbouZor** [comment]
I made the adjustments on the release workflow, and pushed it by mistake directly on the master. This should be closed now, and it will get tested in the next release
